-- ============================================
-- SOAP NOTES SCHEMA REFERENCE
-- One AI SOAP + one Doctor SOAP per encounter
-- Only doctors can add/edit doctor SOAP notes
-- ============================================
-- Use: supabase db push  (or run migration 022)
-- This file is for reference only.

-- 1. AI SOAP (ai_soapnotes) - Generated by AI
--    - encounter_id, appointment_id
--    - One per encounter
--    - Doctors: full access. Nurses: view only.

-- 2. DOCTOR SOAP (doctor_soapnotes) - Written by doctor
CREATE TABLE IF NOT EXISTS public.doctor_soapnotes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  encounter_id BIGINT NOT NULL REFERENCES public.encounters(id) ON DELETE CASCADE,
  doctor_id BIGINT NOT NULL REFERENCES public.doctors(id) ON DELETE CASCADE,
  subjective_text TEXT,
  objective_text TEXT,
  assessment_text TEXT,
  plan_text TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(encounter_id)
);

CREATE INDEX IF NOT EXISTS idx_doctor_soapnotes_encounter_id ON public.doctor_soapnotes(encounter_id);
CREATE INDEX IF NOT EXISTS idx_doctor_soapnotes_doctor_id ON public.doctor_soapnotes(doctor_id);

-- RLS: Only doctors can INSERT/UPDATE. Doctors and nurses can SELECT.
-- See supabase/migrations/022_doctor_soapnotes_and_restrict_add.sql
