-- ============================================
-- category_memr, product_memr, pre_sales for Final Review pre-sales
-- ============================================

-- Category (referenced by product_memr)
CREATE TABLE IF NOT EXISTS public.category_memr (
  id bigserial NOT NULL,
  name text NOT NULL,
  constraint category_memr_pkey primary key (id)
) TABLESPACE pg_default;

-- Product (per category)
CREATE TABLE IF NOT EXISTS public.product_memr (
  id bigserial NOT NULL,
  name text NOT NULL,
  category_id bigint NOT NULL,
  qty_available integer NOT NULL DEFAULT 0,
  constraint product_memr_pkey primary key (id),
  constraint fk_product_category foreign key (category_id) references public.category_memr (id) on update CASCADE on delete RESTRICT
) TABLESPACE pg_default;

-- Pre-sale status enum for pre_sales
DO $$ BEGIN
  CREATE TYPE public.pre_sale_status AS ENUM ('pending', 'completed');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Pre-sales (per encounter)
CREATE TABLE IF NOT EXISTS public.pre_sales (
  id bigint generated by default as identity not null,
  encounter_id bigint null,
  product_id bigint null,
  product_quantity integer not null,
  created_at timestamp with time zone null default now(),
  status public.pre_sale_status null default 'pending',
  constraint pre_sales_pkey primary key (id),
  constraint pre_sales_encounter_id_fkey foreign key (encounter_id) references public.encounters (id) on delete set null,
  constraint pre_sales_product_id_fkey foreign key (product_id) references public.product_memr (id) on delete set null
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_pre_sales_encounter_id ON public.pre_sales(encounter_id);
