-- Multi-tenant clinics: tenants table + tenant_id on locations.

CREATE TABLE IF NOT EXISTS public.tenants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  tenant_code TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  CONSTRAINT tenants_tenant_code_unique UNIQUE (tenant_code)
);

COMMENT ON TABLE public.tenants IS 'Organization / tenant that owns clinic locations.';
COMMENT ON COLUMN public.tenants.tenant_code IS 'Short tenant key shown in admin UI, e.g. 1, 2, 3.';

INSERT INTO public.tenants (id, name, tenant_code)
VALUES (1, 'Default Tenant', '1')
ON CONFLICT (tenant_code) DO NOTHING;

SELECT setval(
  pg_get_serial_sequence('public.tenants', 'id'),
  GREATEST((SELECT COALESCE(MAX(id), 1) FROM public.tenants), 1)
);

ALTER TABLE public.locations
  ADD COLUMN IF NOT EXISTS tenant_id BIGINT REFERENCES public.tenants(id) ON DELETE RESTRICT;

UPDATE public.locations
SET tenant_id = 1
WHERE tenant_id IS NULL;

ALTER TABLE public.locations
  ALTER COLUMN tenant_id SET NOT NULL;

ALTER TABLE public.locations
  ALTER COLUMN tenant_id SET DEFAULT 1;

CREATE INDEX IF NOT EXISTS idx_locations_tenant_id ON public.locations(tenant_id);

COMMENT ON COLUMN public.locations.tenant_id IS 'Owning tenant for this clinic location.';
