-- Separate product catalogs for laboratory services and medications.

CREATE TABLE IF NOT EXISTS public.labs_products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category text NOT NULL,
  product text NOT NULL,
  price numeric(12, 2) NOT NULL CHECK (price >= 0)
);

CREATE INDEX IF NOT EXISTS idx_labs_products_category
  ON public.labs_products (category);

ALTER TABLE public.labs_products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "labs_products_authenticated_read" ON public.labs_products;
CREATE POLICY "labs_products_authenticated_read"
  ON public.labs_products
  FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "labs_products_admin_write" ON public.labs_products;
CREATE POLICY "labs_products_admin_write"
  ON public.labs_products
  FOR ALL
  TO authenticated
  USING (public.is_admin_user())
  WITH CHECK (public.is_admin_user());

CREATE TABLE IF NOT EXISTS public.medication_products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category text NOT NULL,
  product text NOT NULL,
  price numeric(12, 2) NOT NULL CHECK (price >= 0)
);

CREATE INDEX IF NOT EXISTS idx_medication_products_category
  ON public.medication_products (category);

ALTER TABLE public.medication_products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "medication_products_authenticated_read" ON public.medication_products;
CREATE POLICY "medication_products_authenticated_read"
  ON public.medication_products
  FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "medication_products_admin_write" ON public.medication_products;
CREATE POLICY "medication_products_admin_write"
  ON public.medication_products
  FOR ALL
  TO authenticated
  USING (public.is_admin_user())
  WITH CHECK (public.is_admin_user());
