-- Encounter-linked lab and medication orders.
-- Actor identity is recorded in audit_logs by the server API instead of duplicated here.

CREATE TABLE IF NOT EXISTS public.lab_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  encounter_id bigint NOT NULL REFERENCES public.encounters(id) ON DELETE CASCADE,
  lab_product_id bigint NOT NULL REFERENCES public.labs_products(id) ON DELETE RESTRICT,
  qty integer NOT NULL CHECK (qty > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_lab_orders_encounter
  ON public.lab_orders (encounter_id);

ALTER TABLE public.lab_orders ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.medication_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  encounter_id bigint NOT NULL REFERENCES public.encounters(id) ON DELETE CASCADE,
  medication_product_id bigint NOT NULL REFERENCES public.medication_products(id) ON DELETE RESTRICT,
  qty integer NOT NULL CHECK (qty > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_medication_orders_encounter
  ON public.medication_orders (encounter_id);

ALTER TABLE public.medication_orders ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.lab_orders IS
  'Encounter lab orders. Create/update/delete actor identity is stored in public.audit_logs.';

COMMENT ON TABLE public.medication_orders IS
  'Encounter medication orders. Create/update/delete actor identity is stored in public.audit_logs.';
