-- Searchable diagnosis catalog and encounter-linked confirmed diagnoses.
-- The catalog is intentionally empty; rows are loaded separately.

CREATE TABLE IF NOT EXISTS public.all_diagnoses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icd_code TEXT NOT NULL UNIQUE CHECK (length(trim(icd_code)) > 0),
  description TEXT NOT NULL CHECK (length(trim(description)) > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_all_diagnoses_icd_code_lower
  ON public.all_diagnoses (lower(icd_code));

CREATE INDEX IF NOT EXISTS idx_all_diagnoses_description_lower
  ON public.all_diagnoses (lower(description));

CREATE TABLE IF NOT EXISTS public.encounter_diagnoses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  encounter_id BIGINT NOT NULL REFERENCES public.encounters(id) ON DELETE CASCADE,
  diagnosis_id BIGINT NOT NULL REFERENCES public.all_diagnoses(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT encounter_diagnoses_unique_diagnosis UNIQUE (encounter_id, diagnosis_id)
);

CREATE INDEX IF NOT EXISTS idx_encounter_diagnoses_encounter_id
  ON public.encounter_diagnoses (encounter_id);

CREATE INDEX IF NOT EXISTS idx_encounter_diagnoses_diagnosis_id
  ON public.encounter_diagnoses (diagnosis_id);

DROP TRIGGER IF EXISTS update_all_diagnoses_updated_at ON public.all_diagnoses;
CREATE TRIGGER update_all_diagnoses_updated_at
  BEFORE UPDATE ON public.all_diagnoses
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_encounter_diagnoses_updated_at ON public.encounter_diagnoses;
CREATE TRIGGER update_encounter_diagnoses_updated_at
  BEFORE UPDATE ON public.encounter_diagnoses
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

ALTER TABLE public.all_diagnoses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.encounter_diagnoses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Clinical staff read diagnosis catalog" ON public.all_diagnoses;
CREATE POLICY "Clinical staff read diagnosis catalog"
  ON public.all_diagnoses
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE (p.id = auth.uid() OR p.uid = auth.uid())
        AND lower(p.role) IN ('admin', 'doctor', 'fnp', 'pa', 'nurse')
    )
  );

DROP POLICY IF EXISTS "Clinical staff read encounter diagnoses" ON public.encounter_diagnoses;
CREATE POLICY "Clinical staff read encounter diagnoses"
  ON public.encounter_diagnoses
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE (p.id = auth.uid() OR p.uid = auth.uid())
        AND lower(p.role) IN ('admin', 'doctor', 'fnp', 'pa', 'nurse')
    )
  );

COMMENT ON TABLE public.all_diagnoses IS
  'Master ICD diagnosis catalog searched by code and description.';

COMMENT ON TABLE public.encounter_diagnoses IS
  'Confirmed diagnoses selected for an encounter.';
